spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: classpath:static/